<a href="https://colab.research.google.com/github/veeraprathp/Bank-Customer-Churn-Prediction-ANN/blob/main/ANN_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network


In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf


loading the dataset

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')


Data preprocessing

In [4]:
x = dataset.iloc[ :,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data

Label Encoding the data

In [7]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,2]= le.fit_transform(x[:,2])

In [8]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x= np.array(ct.fit_transform(x))

splittin the dataset into the Training set and Test set

In [10]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the tarining set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building the ANN

intializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6,activation ='relu'))


Second layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 6,activation ='relu'))


Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation= 'sigmoid'))

Part 3 - Training the ANN

compiling the ANN

In [17]:
ann.compile(optimizer='adam' , loss='binary_crossentropy',  metrics = ['accuracy'])

Traing the ANN on the Traing set

In [18]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [19]:

print(Y_train)


[0 0 0 ... 0 0 1]


In [20]:
ann.fit(X_train,Y_train,batch_size=32,epochs =100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7648
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.8077
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4328 - accuracy: 0.8151
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4217 - accuracy: 0.8170
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4146 - accuracy: 0.8174
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4084 - accuracy: 0.8194
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8239
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3890 - accuracy: 0.8324
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3781 - accuracy: 0.8394
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3699 - accura

Making the predictions and evaluating the model

In [29]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]) )>0.5)

1/1 [==============================] - 0s 74ms/step
[[False]]


predicting the  Test set Results

In [34]:
y_pred= ann.predict(X_test)
y_pred =(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))


63/63 [==============================] - 0s 4ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


confusion matrix

In [42]:
from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(Y_test,y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[1578   17]
 [ 316   89]]


0.8335